#!/bin/sh
# Setup a machine for Sublime Text 3
set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/
mv "$sublime_dir/Packages" "$sublime_dir/Packages.backup"
ln -s "$ZSH/sublime3/Packages" "$sublime_dir/"

# Grab the Soda theme
# cd "$sublime_dir"
# git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"
